name: Delete all Packages

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Delete all Packages
      run: |
          curl -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/Armatiek/packages/maven/imvertor_arm.imvertor_arm"
