name: Delete all Packages

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/delete-package-versions@v4.1.1
      with:
        owner: 'github'
        package-name: 'imvertor_arm.imvertor_arm'
        package-type: 'maven'
        min-versions-to-keep: 0
