name: Delete all Packages 2

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Delete all Packages 2
      uses: actions/delete-package-versions@v4
      with: 
        package-name: 'imvertor_arm.imvertor.arm'
        package-type: 'maven'
        min-versions-to-keep: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        ignore-versions: '^(?!3\.0\.0$)'
