name: Get package versions

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get package versions
      uses: actions/github-script@v7
      id: get-versions
      with:
        result-encoding: string
        retries: 3
        script: |
          const versions = github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
            package_type: 'maven',
            package_name: 'imvertor_arm.imvertor_arm',
            org: 'Armatiek' ,
          })
          console.log(versions)
