name: Get package versions

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get package versions
      uses: actions/github-script@v7
      id: get-versions
      with:
        script: |
          const versionInfo = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
            package_type: 'maven',
            package_name: 'imvertor_arm.imvertor_arm',
            org: 'Armatiek',
          })
          console.log(versionInfo)
          const versions = versionInfo.data
          for (const version of versions) {
            if (version.name == '3.0.0') {
              console.log(version.id)
            }
          }
          
