name: Purge workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '45 3 * * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Purge workflow runs
        uses: boredland/action-purge-workflow-runs@main
        with:
          days-old: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
